//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVA.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FARToBeVerified
    {
        public string ID { get; set; }
        public string PlantID { get; set; }
        public string AssetIDSubNo { get; set; }
        public string Process { get; set; }
        public string Product { get; set; }
        public string Pack { get; set; }
        public string EquipmentDetails { get; set; }
        public string AssetDescription { get; set; }
        public string InstallationStatus { get; set; }
        public string AssetImage { get; set; }
        public string BarCodeImage { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EnteredOnMachineID { get; set; }
        public string ExeVersionNo { get; set; }
        public string ModuleName { get; set; }
        public string APSyncModifiedBy { get; set; }
        public Nullable<System.DateTime> SysCreatedDateTime { get; set; }
        public Nullable<System.DateTime> SysModifiedDateTime { get; set; }
        public string AssetQRCode { get; set; }
        public string VerifiedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string Vendor { get; set; }
        public string RejectionRemarks { get; set; }
        public string Type { get; set; }
    }
}
