//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVA.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantAreaMaster
    {
        public string ID { get; set; }
        public string PLANT { get; set; }
        public string BA { get; set; }
        public string PLANT_NAME { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string StartedBy { get; set; }
        public string CompletedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EnteredOnMachineID { get; set; }
        public string ExeVersionNo { get; set; }
        public string ModuleName { get; set; }
        public string APSyncModifiedBy { get; set; }
        public Nullable<System.DateTime> SysCreatedDateTime { get; set; }
        public Nullable<System.DateTime> SysModifiedDateTime { get; set; }
    }
}
