//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVA.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginDetail
    {
        public string ID { get; set; }
        public string UserType { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string MobileNo { get; set; }
        public string LandLineNo { get; set; }
        public string EmailAddress { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EnteredOnMachineID { get; set; }
        public string ExeVersionNo { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ModuleName { get; set; }
        public string Gender { get; set; }
        public string Salutation { get; set; }
        public string FaxNo { get; set; }
        public Nullable<bool> IsEmailAddressVerified { get; set; }
        public Nullable<bool> IsVerificationMailSend { get; set; }
        public string CircleId { get; set; }
        public string Zone { get; set; }
        public Nullable<System.DateTime> LastQueryDateTime { get; set; }
        public Nullable<int> PendingRowsCount { get; set; }
        public Nullable<int> PendingImageCount { get; set; }
        public string ApkVersionNo { get; set; }
        public Nullable<System.DateTime> DataSyncDateTime { get; set; }
        public string DeviceID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyCode { get; set; }
        public string APSyncModifiedBy { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> SysCreatedDateTime { get; set; }
        public Nullable<System.DateTime> SysModifiedDateTime { get; set; }
        public Nullable<bool> ScanOnly { get; set; }
        public Nullable<bool> ScanOnly2 { get; set; }
        public Nullable<bool> MFScanOnly { get; set; }
        public string PVAgencyName { get; set; }
        public Nullable<bool> isDemoUser { get; set; }
    }
}
